// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmedhmboyjkunxbhpzxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZWRobWJveWprdW54YmhwenhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTIwNTQsImV4cCI6MjA3MTAyODA1NH0.DqCHv0M8te-CrICAu_bA8MSiVh3g3380cIuzsTNWNwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});