// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrznupxtmtesagrdaiyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyem51cHh0bXRlc2FncmRhaXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Nzg2NDAsImV4cCI6MjA3MzE1NDY0MH0.r5ufwqpo6BtXL9PNcA1CLlpIh3_pxuyjOKvQvy2llPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});